### ISSUE TITLE
`invalid pthread_t passed to libc` bug

### ISSUE THREAD

**Issue by croissanne** [croissanne/portaudio_opensles#14]
Android >= 27 included some [changes](https://github.com/aosp-mirror/platform_bionic/blob/94a62765b0d5e180e9b81280ae485cad3cb34e20/libc/bionic/pthread_internal.cpp#L106) to  __pthread_internal_find which I think trips up portaudio in scenarios like `test/patest_callback.c`. Might need to create the streaming thread differently or clean up the old one differently?

**Comment by darksylinc** [comment]
This is probably addressed by https://github.com/croissanne/portaudio_opensles/pull/17

I noticed my app started randomly crashing after upgrading to latest OpenSL ES and made a thorough review of the changes.

After fixing that corruption, the crashes were gone.
